import { createHash } from 'node:crypto';
import { OBSERVATION_SCHEMA, validateObservation } from './visual-observation.mjs';

export const LEDGER_SCHEMA = 'phase1-ledger-v2';
export { OBSERVATION_SCHEMA, validateObservation };
export const DIFF_SCHEMA = 'phase1-visual-diff-v1';
export const ANSWER_SOURCES = Object.freeze(['memory', 'profile', 'resume', 'agent_inference', 'user']);
export const CANDIDATE_CLASSES = Object.freeze(['field', 'non_final_navigation', 'final_candidate', 'unknown']);

const SOURCES = new Set(ANSWER_SOURCES);
const CLASSES = new Set(CANDIDATE_CLASSES);
const CHOICES = new Set(['blank', 'decline', 'not_applicable', 'prefer_not_to_answer', 'none']);
const STATES = new Set(['blank', 'present', 'selected', 'unknown']);
const ACTIONS = new Set(['click', 'type_text', 'press_key', 'scroll', 'upload_file', 'non_final_navigation', 'final_submit']);
const OUTCOMES = new Set(['attempted', 'succeeded', 'failed', 'blocked', 'retry', 'stale']);
const TERMINAL = new Set(['succeeded', 'failed', 'blocked']);
const MUTATIONS = new Set(['click', 'type_text', 'press_key', 'upload_file', 'non_final_navigation']);
const TARGET_MUTATIONS = new Set(['click', 'type_text', 'press_key', 'upload_file']);
const DIGEST = /^[a-f0-9]{64}$/;
const ID = /^(?!\s)[^\u0000-\u001f\u007f]{1,512}$/;
const BASENAME = /^(?!\.{1,2}$)(?!\s)[^/\\\u0000-\u001f\u007f]{1,255}$/;

const LEDGER_KEYS = new Set(['schema', 'latest_observation_id', 'observation_ids', 'targets', 'diffs', 'action_attempts', 'submit_action_count', 'unknown_targets', 'active_blockers', 'current_candidate_targets']);
const TARGET_KEYS = new Set(['field_id', 'target_id', 'kind', 'group_id', 'label', 'description', 'target_history', 'latest_observation_id', 'present_in_latest_observation', 'reachable', 'visible', 'enabled', 'required', 'readonly', 'optional', 'sensitive', 'final', 'latest_state', 'answer_state', 'answer_source', 'value_digest', 'semantic_choice', 'inference_rationale_digest', 'inference_evidence_digests', 'retained', 'valid', 'retry_notes', 'revealed_observation_id', 'last_revealed_observation_id']);
const STATE_KEYS = new Set(['value_state', 'checked', 'selected', 'option_states', 'validation', 'file']);
const ACTION_KEYS = new Set(['action_id', 'action', 'field_id', 'observation_id', 'target_id', 'outcome', 'retry_of', 'error_code', 'stale_target']);
const PROOF_KEYS = new Set(['action_id', 'visually_confirmed', 'file_name']);

export class Phase1SchemaError extends TypeError {
  constructor(message, code = 'SCHEMA_INVALID') { super(message); this.name = 'Phase1SchemaError'; this.code = code; }
}
export class Phase1StaleReferenceError extends Error {
  constructor(message = 'observation or target binding is stale') { super(message); this.name = 'Phase1StaleReferenceError'; this.code = 'STALE_TARGET'; }
}

function fail(path, message, code = 'SCHEMA_INVALID') { throw new Phase1SchemaError(`${path}: ${message}`, code); }
function record(value, path) { if (value === null || typeof value !== 'object' || Array.isArray(value)) fail(path, 'expected an object'); }
function exact(value, allowed, path) { for (const key of Object.keys(value)) if (!allowed.has(key)) fail(`${path}.${key}`, 'unknown key'); }
function required(value, keys, path) { for (const key of keys) if (!Object.hasOwn(value, key)) fail(`${path}.${key}`, 'missing key'); }
function string(value, path, { nullable = false, identifier = false, max = 4096 } = {}) { if (nullable && value === null) return; if (typeof value !== 'string' || value.length > max || (identifier && !ID.test(value))) fail(path, 'invalid string'); }
function boolean(value, path, nullable = false) { if (nullable && value === null) return; if (typeof value !== 'boolean') fail(path, 'expected a boolean'); }
function integer(value, path, minimum = 0) { if (!Number.isSafeInteger(value) || value < minimum) fail(path, 'expected a bounded integer'); }
function array(value, path) { if (!Array.isArray(value)) fail(path, 'expected an array'); }
function clone(value) { if (Array.isArray(value)) return value.map(clone); if (value !== null && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, clone(item)])); return value; }
function freeze(value) { if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) { for (const child of Object.values(value)) freeze(child); Object.freeze(value); } return value; }
function immutable(value) { return freeze(clone(value)); }
function digest(value, path, nullable = true) { if (value === null && nullable) return; if (typeof value !== 'string' || !DIGEST.test(value)) fail(path, 'expected a SHA-256 digest'); }
function selected(value, path) { if (value === null || typeof value === 'boolean') return; if (!Array.isArray(value) || !value.every((item) => typeof item === 'string')) fail(path, 'invalid selection state'); }

function validateState(value, path) {
  record(value, path); exact(value, STATE_KEYS, path); required(value, [...STATE_KEYS], path);
  string(value.value_state, `${path}.value_state`, { identifier: true }); if (!STATES.has(value.value_state)) fail(`${path}.value_state`, 'invalid value state');
  boolean(value.checked, `${path}.checked`, true); selected(value.selected, `${path}.selected`); array(value.option_states, `${path}.option_states`);
  value.option_states.forEach((item, index) => { const p = `${path}.option_states[${index}]`; record(item, p); exact(item, new Set(['label', 'selected', 'disabled']), p); required(item, ['label', 'selected', 'disabled'], p); string(item.label, `${p}.label`, { nullable: true }); boolean(item.selected, `${p}.selected`); boolean(item.disabled, `${p}.disabled`); });
  record(value.validation, `${path}.validation`); exact(value.validation, new Set(['valid', 'message_present']), `${path}.validation`); required(value.validation, ['valid', 'message_present'], `${path}.validation`); boolean(value.validation.valid, `${path}.validation.valid`, true); boolean(value.validation.message_present, `${path}.validation.message_present`);
  record(value.file, `${path}.file`); exact(value.file, new Set(['present', 'file_name']), `${path}.file`); required(value.file, ['present', 'file_name'], `${path}.file`); boolean(value.file.present, `${path}.file.present`); if (value.file.file_name !== null && (typeof value.file.file_name !== 'string' || !BASENAME.test(value.file.file_name))) fail(`${path}.file.file_name`, 'invalid basename');
}
function validateTarget(value, path) {
  record(value, path); exact(value, TARGET_KEYS, path); required(value, [...TARGET_KEYS], path);
  string(value.field_id, `${path}.field_id`, { identifier: true }); string(value.target_id, `${path}.target_id`, { identifier: true }); string(value.kind, `${path}.kind`, { identifier: true }); string(value.group_id, `${path}.group_id`, { identifier: true, nullable: true }); string(value.label, `${path}.label`, { nullable: true }); string(value.description, `${path}.description`, { nullable: true });
  array(value.target_history, `${path}.target_history`); value.target_history.forEach((item, index) => { const p = `${path}.target_history[${index}]`; record(item, p); exact(item, new Set(['observation_id', 'target_id']), p); required(item, ['observation_id', 'target_id'], p); string(item.observation_id, `${p}.observation_id`, { identifier: true }); string(item.target_id, `${p}.target_id`, { identifier: true }); }); string(value.latest_observation_id, `${path}.latest_observation_id`, { identifier: true });
  for (const key of ['present_in_latest_observation', 'reachable', 'visible', 'enabled', 'required', 'readonly', 'optional', 'sensitive', 'final', 'retained', 'valid']) boolean(value[key], `${path}.${key}`); validateState(value.latest_state, `${path}.latest_state`);
  string(value.answer_state, `${path}.answer_state`, { identifier: true }); if (!new Set(['unresolved', 'answered', 'blank']).has(value.answer_state)) fail(`${path}.answer_state`, 'invalid answer state'); string(value.answer_source, `${path}.answer_source`, { identifier: true, nullable: true }); if (value.answer_source !== null && !SOURCES.has(value.answer_source)) fail(`${path}.answer_source`, 'invalid answer source'); digest(value.value_digest, `${path}.value_digest`); string(value.semantic_choice, `${path}.semantic_choice`, { identifier: true, nullable: true }); if (value.semantic_choice !== null && !CHOICES.has(value.semantic_choice)) fail(`${path}.semantic_choice`, 'invalid semantic choice'); digest(value.inference_rationale_digest, `${path}.inference_rationale_digest`); if (value.inference_evidence_digests !== null) { record(value.inference_evidence_digests, `${path}.inference_evidence_digests`); exact(value.inference_evidence_digests, new Set(['resume_sha256', 'job_description_sha256']), `${path}.inference_evidence_digests`); required(value.inference_evidence_digests, ['resume_sha256', 'job_description_sha256'], `${path}.inference_evidence_digests`); digest(value.inference_evidence_digests.resume_sha256, `${path}.inference_evidence_digests.resume_sha256`, false); digest(value.inference_evidence_digests.job_description_sha256, `${path}.inference_evidence_digests.job_description_sha256`, false); }
  if (value.answer_state === 'unresolved' && (value.answer_source !== null || value.value_digest !== null || value.semantic_choice !== null || value.inference_rationale_digest !== null || value.inference_evidence_digests !== null)) fail(`${path}.answer_state`, 'unresolved target cannot carry an answer'); if (value.answer_state === 'answered' && (value.answer_source === null || value.value_digest === null)) fail(`${path}.answer_state`, 'answered target requires an answer'); if (value.answer_state === 'blank' && (value.answer_source === null || value.semantic_choice === null)) fail(`${path}.answer_state`, 'blank target requires deliberate state'); if (value.answer_source === 'agent_inference' && (value.inference_rationale_digest === null || value.inference_evidence_digests === null)) fail(`${path}.answer_source`, 'inference metadata required'); if (value.answer_source !== 'agent_inference' && (value.inference_rationale_digest !== null || value.inference_evidence_digests !== null)) fail(`${path}.answer_source`, 'inference metadata not allowed'); array(value.retry_notes, `${path}.retry_notes`); value.retry_notes.forEach((item, index) => string(item, `${path}.retry_notes[${index}]`, { identifier: true })); string(value.revealed_observation_id, `${path}.revealed_observation_id`, { identifier: true, nullable: true }); string(value.last_revealed_observation_id, `${path}.last_revealed_observation_id`, { identifier: true, nullable: true });
}
function validateAction(value, path) {
  record(value, path); exact(value, ACTION_KEYS, path); required(value, [...ACTION_KEYS], path); string(value.action_id, `${path}.action_id`, { identifier: true }); string(value.action, `${path}.action`, { identifier: true }); if (!ACTIONS.has(value.action)) fail(`${path}.action`, 'invalid action'); string(value.field_id, `${path}.field_id`, { identifier: true, nullable: true }); string(value.observation_id, `${path}.observation_id`, { identifier: true }); string(value.target_id, `${path}.target_id`, { identifier: true, nullable: true }); string(value.outcome, `${path}.outcome`, { identifier: true }); if (!OUTCOMES.has(value.outcome)) fail(`${path}.outcome`, 'invalid outcome'); if (value.retry_of !== null) integer(value.retry_of, `${path}.retry_of`); string(value.error_code, `${path}.error_code`, { identifier: true, nullable: true }); boolean(value.stale_target, `${path}.stale_target`);
  if (TARGET_MUTATIONS.has(value.action) && (value.field_id === null || value.target_id === null)) fail(path, 'target mutation requires field and target'); if (value.action === 'non_final_navigation' && (value.field_id !== null || value.target_id === null)) fail(path, 'navigation requires target only'); if (value.action === 'final_submit' && (value.field_id !== null || value.target_id === null)) fail(path, 'submission requires target only'); if (value.action === 'scroll' && (value.field_id !== null || value.target_id !== null)) fail(path, 'scroll does not accept target');
}
function validateLedgerShape(value) {
  record(value, 'ledger'); exact(value, LEDGER_KEYS, 'ledger'); required(value, [...LEDGER_KEYS], 'ledger'); if (value.schema !== LEDGER_SCHEMA) fail('ledger.schema', 'unexpected schema'); string(value.latest_observation_id, 'ledger.latest_observation_id', { identifier: true, nullable: true }); array(value.observation_ids, 'ledger.observation_ids'); const ids = new Set(); value.observation_ids.forEach((item, index) => { string(item, `ledger.observation_ids[${index}]`, { identifier: true }); if (ids.has(item)) fail(`ledger.observation_ids[${index}]`, 'duplicate observation'); ids.add(item); }); if ((value.latest_observation_id === null) !== (value.observation_ids.length === 0) || (value.latest_observation_id !== null && value.observation_ids.at(-1) !== value.latest_observation_id)) fail('ledger.observation_ids', 'latest observation mismatch');
  array(value.targets, 'ledger.targets'); const fields = new Set(); value.targets.forEach((item, index) => { validateTarget(item, `ledger.targets[${index}]`); if (fields.has(item.field_id)) fail(`ledger.targets[${index}].field_id`, 'duplicate field'); fields.add(item.field_id); }); array(value.diffs, 'ledger.diffs'); array(value.action_attempts, 'ledger.action_attempts'); const actions = new Set(); value.action_attempts.forEach((item, index) => { validateAction(item, `ledger.action_attempts[${index}]`); if (actions.has(item.action_id)) fail(`ledger.action_attempts[${index}].action_id`, 'duplicate action'); actions.add(item.action_id); }); integer(value.submit_action_count, 'ledger.submit_action_count'); if (value.submit_action_count !== value.action_attempts.filter((item) => item.action === 'final_submit').length) fail('ledger.submit_action_count', 'submission count mismatch'); array(value.unknown_targets, 'ledger.unknown_targets'); value.unknown_targets.forEach((item, index) => { const p = `ledger.unknown_targets[${index}]`; record(item, p); exact(item, new Set(['target_id', 'observation_id', 'reason']), p); required(item, ['target_id', 'observation_id', 'reason'], p); string(item.target_id, `${p}.target_id`, { identifier: true }); string(item.observation_id, `${p}.observation_id`, { identifier: true }); string(item.reason, `${p}.reason`, { nullable: true }); }); array(value.active_blockers, 'ledger.active_blockers'); value.active_blockers.forEach((item, index) => string(item, `ledger.active_blockers[${index}]`, { identifier: true })); array(value.current_candidate_targets, 'ledger.current_candidate_targets'); value.current_candidate_targets.forEach((item, index) => { const p = `ledger.current_candidate_targets[${index}]`; record(item, p); exact(item, new Set(['target_id', 'observation_id', 'class']), p); required(item, ['target_id', 'observation_id', 'class'], p); string(item.target_id, `${p}.target_id`, { identifier: true }); string(item.observation_id, `${p}.observation_id`, { identifier: true }); string(item.class, `${p}.class`, { identifier: true }); if (!CLASSES.has(item.class) || item.class === 'field' || item.observation_id !== value.latest_observation_id) fail(p, 'invalid candidate target'); });
}
export function validateLedger(value) { validateLedgerShape(value); return true; }

function normalizeBlocker(item) { return typeof item === 'string' ? item : item.code; }
function isHoneypot(target) { return /honeypot|trap[-_ ]?field|bot[-_ ]?field/.test(`${target.candidate.reason ?? ''} ${target.label ?? ''} ${target.description ?? ''}`.toLowerCase()); }
function isReachable(target) { return target.candidate.class === 'field' && target.visible && target.enabled && !isHoneypot(target); }
export function isReachableTarget(target) { return isReachable(target); }
export function isHoneypotTarget(target) { return isHoneypot(target); }
function stateFromTarget(target) { return { value_state: target.value_state, checked: target.checked, selected: target.selected === null ? null : clone(target.selected), option_states: target.options.map((item) => ({ label: item.label, selected: item.selected, disabled: item.disabled })), validation: { valid: target.validation.valid, message_present: target.validation.message_present }, file: target.file === null ? { present: false, file_name: null } : { present: target.file.present, file_name: target.file.file_name } }; }
function equal(left, right) { if (Object.is(left, right)) return true; if (Array.isArray(left) && Array.isArray(right)) return left.length === right.length && left.every((item, index) => equal(item, right[index])); if (left !== null && right !== null && typeof left === 'object' && typeof right === 'object') { const a = Object.keys(left); const b = Object.keys(right); return a.length === b.length && a.every((key) => key in right && equal(left[key], right[key])); } return false; }
function makeTarget(target, observationId, previous = null) { const reachable = isReachable(target); const changed = previous !== null && previous.target_id !== target.target_id; const returned = previous !== null && !previous.present_in_latest_observation && reachable; const lostFile = previous?.answer_state === 'answered' && previous.latest_state.file.present && !(target.file?.present === true); const carry = previous?.answer_state && previous.answer_state !== 'unresolved' && !changed && !returned && !lostFile; const history = previous ? previous.target_history.map(clone) : []; if (!history.some((item) => item.observation_id === observationId && item.target_id === target.target_id)) history.push({ observation_id: observationId, target_id: target.target_id }); const fieldId = target.field_id ?? target.target_id; return { field_id: fieldId, target_id: target.target_id, kind: target.kind, group_id: target.group_id, label: target.label, description: target.description, target_history: history, latest_observation_id: observationId, present_in_latest_observation: true, reachable, visible: target.visible, enabled: target.enabled, required: target.required, readonly: target.readonly, optional: !target.required, sensitive: previous?.sensitive ?? false, final: target.candidate.class === 'final_candidate', latest_state: stateFromTarget(target), answer_state: previous?.answer_state ?? 'unresolved', answer_source: previous?.answer_source ?? null, value_digest: previous?.value_digest ?? null, semantic_choice: previous?.semantic_choice ?? null, inference_rationale_digest: previous?.inference_rationale_digest ?? null, inference_evidence_digests: previous?.inference_evidence_digests ? clone(previous.inference_evidence_digests) : null, retained: carry ? previous.retained : false, valid: carry ? previous.valid : false, retry_notes: previous ? [...previous.retry_notes] : [], revealed_observation_id: previous?.revealed_observation_id ?? (reachable ? observationId : null), last_revealed_observation_id: reachable && (!previous || !previous.reachable || returned) ? observationId : (previous?.last_revealed_observation_id ?? null) }; }
function absent(item) { const lost = item.answer_state === 'answered' && item.latest_state.file.present; return { ...item, present_in_latest_observation: false, reachable: false, retained: lost ? false : item.retained, valid: lost ? false : item.valid }; }
function diff(previousId, nextId, before, after, addedBlockers, removedBlockers) { const added = []; const removed = []; const changed = []; const beforeMap = new Map(before.map((item) => [item.field_id, item])); const afterMap = new Map(after.map((item) => [item.field_id, item])); for (const item of after) { const old = beforeMap.get(item.field_id); if (!old || !old.present_in_latest_observation) added.push({ field_id: item.field_id, target_id: item.target_id, kind: item.kind }); else { const changes = []; for (const property of ['target_id', 'kind', 'group_id', 'label', 'description', 'visible', 'enabled', 'required', 'readonly', 'latest_state', 'reachable']) if (!equal(old[property], item[property])) changes.push({ property, from: clone(old[property]), to: clone(item[property]) }); if (changes.length) changed.push({ field_id: item.field_id, changes }); } } for (const item of before) if (item.present_in_latest_observation && !afterMap.get(item.field_id)?.present_in_latest_observation) removed.push({ field_id: item.field_id, target_id: item.target_id, kind: item.kind }); return immutable({ schema: DIFF_SCHEMA, from_observation_id: previousId, to_observation_id: nextId, added, removed, changed, blockers_added: addedBlockers, blockers_removed: removedBlockers }); }
export function diffObservations(previous, next) { if (previous !== null) validateObservation(previous); validateObservation(next); if (previous && next.previous_observation_id !== previous.observation_id) throw new Phase1StaleReferenceError('observation chain does not match'); const before = previous?.targets.filter((item) => item.candidate.class === 'field').map((item) => makeTarget(item, previous.observation_id)) ?? []; const after = next.targets.filter((item) => item.candidate.class === 'field').map((item) => makeTarget(item, next.observation_id)); const oldBlockers = new Set(previous?.blockers.map(normalizeBlocker) ?? []); const newBlockers = new Set(next.blockers.map(normalizeBlocker)); return diff(previous?.observation_id ?? null, next.observation_id, before, after, [...newBlockers].filter((item) => !oldBlockers.has(item)).sort(), [...oldBlockers].filter((item) => !newBlockers.has(item)).sort()); }

function empty() { return { schema: LEDGER_SCHEMA, latest_observation_id: null, observation_ids: [], targets: [], diffs: [], action_attempts: [], submit_action_count: 0, unknown_targets: [], active_blockers: [], current_candidate_targets: [] }; }
export function createLedger(initialObservation = null) { return initialObservation === null ? immutable(empty()) : mergeObservation(immutable(empty()), initialObservation); }
export function mergeObservation(ledger, observation) {
  validateLedgerShape(ledger); validateObservation(observation); if (ledger.latest_observation_id === null) { if (observation.previous_observation_id !== null) throw new Phase1StaleReferenceError('first observation cannot point backward'); } else if (observation.previous_observation_id !== ledger.latest_observation_id) throw new Phase1StaleReferenceError('observation is not the next image'); if (ledger.observation_ids.includes(observation.observation_id)) throw new Phase1StaleReferenceError('observation was already merged');
  const previous = ledger.targets; const byField = new Map(previous.map((item) => [item.field_id, item])); const visible = observation.targets.filter((item) => item.candidate.class === 'field'); const byId = new Map(previous.map((item) => [item.field_id, absent(item)])); for (const item of visible) { const next = makeTarget(item, observation.observation_id, byField.get(item.field_id ?? item.target_id)); byId.set(next.field_id, next); } const targets = []; const seen = new Set(); for (const item of previous) { const next = byId.get(item.field_id); if (next) { targets.push(next); seen.add(item.field_id); } } for (const item of visible) { const fieldId = item.field_id ?? item.target_id; if (!seen.has(fieldId)) { targets.push(byId.get(fieldId)); seen.add(fieldId); } }
  const unknownTargets = [...ledger.unknown_targets.filter((item) => item.observation_id !== observation.observation_id), ...observation.targets.filter((item) => item.candidate.class === 'unknown' && item.visible && item.enabled && !isHoneypot(item)).map((item) => ({ target_id: item.target_id, observation_id: observation.observation_id, reason: item.candidate.reason }))]; const blockers = [...new Set(observation.blockers.map(normalizeBlocker))].sort(); const candidateTargets = observation.targets.filter((item) => (item.candidate.class === 'non_final_navigation' || item.candidate.class === 'final_candidate') && item.visible && item.enabled && !isHoneypot(item)).map((item) => ({ target_id: item.target_id, observation_id: observation.observation_id, class: item.candidate.class })).sort((a, b) => `${a.target_id}\u0000${a.class}`.localeCompare(`${b.target_id}\u0000${b.class}`)); const oldBlockers = ledger.active_blockers; const change = diff(ledger.latest_observation_id, observation.observation_id, previous, targets, blockers.filter((item) => !oldBlockers.includes(item)), oldBlockers.filter((item) => !blockers.includes(item))); return immutable({ ...clone(ledger), latest_observation_id: observation.observation_id, observation_ids: [...ledger.observation_ids, observation.observation_id], targets, diffs: [...ledger.diffs, change], unknown_targets: unknownTargets, active_blockers: blockers, current_candidate_targets: candidateTargets });
}

function normalizeResolution(input) { record(input, 'resolution'); const allowed = new Set(['field_id', 'observation_id', 'target_id', 'source', 'value_digest', 'semantic_choice', 'inference_rationale_digest', 'inference_evidence_digests', 'sensitive']); exact(input, allowed, 'resolution'); required(input, ['field_id', 'observation_id', 'target_id', 'source'], 'resolution'); string(input.field_id, 'resolution.field_id', { identifier: true }); string(input.observation_id, 'resolution.observation_id', { identifier: true }); string(input.target_id, 'resolution.target_id', { identifier: true }); string(input.source, 'resolution.source', { identifier: true }); if (!SOURCES.has(input.source)) fail('resolution.source', 'invalid answer source'); const valueDigest = input.value_digest ?? null; digest(valueDigest, 'resolution.value_digest'); const choice = input.semantic_choice ?? null; string(choice, 'resolution.semantic_choice', { identifier: true, nullable: true }); if (choice !== null && !CHOICES.has(choice)) fail('resolution.semantic_choice', 'invalid choice'); if (valueDigest === null && choice === null) fail('resolution', 'digest or deliberate choice required'); const rationale = input.inference_rationale_digest ?? null; digest(rationale, 'resolution.inference_rationale_digest'); const evidence = input.inference_evidence_digests ?? null; if (evidence !== null) { record(evidence, 'resolution.inference_evidence_digests'); exact(evidence, new Set(['resume_sha256', 'job_description_sha256']), 'resolution.inference_evidence_digests'); required(evidence, ['resume_sha256', 'job_description_sha256'], 'resolution.inference_evidence_digests'); digest(evidence.resume_sha256, 'resolution.inference_evidence_digests.resume_sha256', false); digest(evidence.job_description_sha256, 'resolution.inference_evidence_digests.job_description_sha256', false); } if (input.source === 'agent_inference' && (rationale === null || evidence === null)) fail('resolution', 'inference metadata required'); if (input.source !== 'agent_inference' && (rationale !== null || evidence !== null)) fail('resolution', 'inference metadata not allowed'); if (input.sensitive !== undefined) boolean(input.sensitive, 'resolution.sensitive'); return { ...input, value_digest: valueDigest, semantic_choice: choice, inference_rationale_digest: rationale, inference_evidence_digests: evidence === null ? null : clone(evidence) }; }
export function recordResolution(ledger, input) { validateLedgerShape(ledger); const resolution = normalizeResolution(input); const index = ledger.targets.findIndex((item) => item.field_id === resolution.field_id); if (index < 0) fail('resolution.field_id', 'unknown field', 'UNKNOWN_FIELD'); const target = ledger.targets[index]; if (ledger.latest_observation_id !== resolution.observation_id || target.latest_observation_id !== resolution.observation_id || target.target_id !== resolution.target_id || !target.present_in_latest_observation || !target.reachable || target.final) throw new Phase1StaleReferenceError('resolution target is stale'); if (resolution.source === 'agent_inference' && (resolution.sensitive === true || target.sensitive)) fail('resolution.source', 'inference prohibited for sensitive target'); const targets = ledger.targets.map((item, itemIndex) => itemIndex === index ? { ...item, answer_state: resolution.value_digest === null ? 'blank' : 'answered', answer_source: resolution.source, value_digest: resolution.value_digest, semantic_choice: resolution.semantic_choice, inference_rationale_digest: resolution.inference_rationale_digest, inference_evidence_digests: resolution.inference_evidence_digests, sensitive: resolution.sensitive ?? item.sensitive, retained: false, valid: false } : item); return immutable({ ...clone(ledger), targets }); }
export function markTargetSensitive(ledger, fieldId) { validateLedgerShape(ledger); string(fieldId, 'field_id', { identifier: true }); const index = ledger.targets.findIndex((item) => item.field_id === fieldId); if (index < 0) fail('field_id', 'unknown field', 'UNKNOWN_FIELD'); const target = ledger.targets[index]; const derived = target.answer_source === 'resume' || target.answer_source === 'agent_inference'; if (target.sensitive && !derived) return ledger; const targets = ledger.targets.map((item, itemIndex) => itemIndex === index ? { ...item, sensitive: true, answer_state: derived ? 'unresolved' : item.answer_state, answer_source: derived ? null : item.answer_source, value_digest: derived ? null : item.value_digest, semantic_choice: derived ? null : item.semantic_choice, inference_rationale_digest: derived ? null : item.inference_rationale_digest, inference_evidence_digests: derived ? null : item.inference_evidence_digests, retained: derived ? false : item.retained, valid: derived ? false : item.valid } : item); return immutable({ ...clone(ledger), targets }); }
export const markFieldSensitive = markTargetSensitive;

function normalizeAction(input, sequence) { record(input, 'action'); exact(input, ACTION_KEYS, 'action'); required(input, ['action', 'observation_id'], 'action'); const actionId = input.action_id ?? `action-${sequence}`; string(actionId, 'action.action_id', { identifier: true }); string(input.action, 'action.action', { identifier: true }); if (!ACTIONS.has(input.action)) fail('action.action', 'invalid action'); const fieldId = input.field_id ?? null; string(fieldId, 'action.field_id', { identifier: true, nullable: true }); string(input.observation_id, 'action.observation_id', { identifier: true }); const targetId = input.target_id ?? null; string(targetId, 'action.target_id', { identifier: true, nullable: true }); const outcome = input.outcome ?? 'attempted'; string(outcome, 'action.outcome', { identifier: true }); if (!OUTCOMES.has(outcome)) fail('action.outcome', 'invalid outcome'); if (input.action === 'final_submit' && outcome !== 'attempted') fail('action.outcome', 'submission begins attempted'); const retryOf = input.retry_of ?? null; if (retryOf !== null) integer(retryOf, 'action.retry_of'); const errorCode = input.error_code ?? null; string(errorCode, 'action.error_code', { identifier: true, nullable: true }); const staleTarget = input.stale_target ?? false; boolean(staleTarget, 'action.stale_target'); return { action_id: actionId, action: input.action, field_id: fieldId, observation_id: input.observation_id, target_id: targetId, outcome, retry_of: retryOf, error_code: errorCode, stale_target: staleTarget }; }
function bind(ledger, action) { if (TARGET_MUTATIONS.has(action.action)) { const target = ledger.targets.find((item) => item.field_id === action.field_id); if (!target) fail('action.field_id', 'unknown field', 'UNKNOWN_FIELD'); if (!target.present_in_latest_observation || !target.reachable || target.latest_observation_id !== ledger.latest_observation_id || target.target_id !== action.target_id || !target.target_history.some((item) => item.observation_id === action.observation_id && item.target_id === action.target_id)) throw new Phase1StaleReferenceError('action target is stale'); return target; } if (action.action === 'non_final_navigation' || action.action === 'final_submit') { const candidate = ledger.current_candidate_targets.find((item) => item.observation_id === action.observation_id && item.target_id === action.target_id); if (!candidate || candidate.class !== (action.action === 'final_submit' ? 'final_candidate' : 'non_final_navigation')) throw new Phase1StaleReferenceError('candidate target is stale or wrong class'); } return null; }
function consumed(ledger, observationId = ledger.latest_observation_id) { return ledger.action_attempts.some((item) => item.observation_id === observationId && MUTATIONS.has(item.action) && !item.stale_target); }
export function requiresReobservation(ledger) { validateLedgerShape(ledger); return consumed(ledger); }
function appendAction(ledger, action, allowConsumed = false) { if (ledger.action_attempts.some((item) => item.action_id === action.action_id)) fail('action.action_id', 'duplicate action'); if (action.action === 'final_submit' && ledger.action_attempts.some((item) => item.action === 'final_submit' && item.outcome === 'attempted')) fail('action.action', 'submission pending', 'PENDING_FINAL_SUBMIT'); if (action.observation_id !== ledger.latest_observation_id) throw new Phase1StaleReferenceError('action observation is stale'); if (!allowConsumed && TARGET_MUTATIONS.has(action.action) && consumed(ledger)) throw new Phase1StaleReferenceError('observe again after mutation'); bind(ledger, action); const targets = TARGET_MUTATIONS.has(action.action) && action.field_id !== null ? ledger.targets.map((item) => item.field_id === action.field_id ? { ...item, retained: false, valid: false, retry_notes: action.error_code && !item.retry_notes.includes(action.error_code) ? [...item.retry_notes, action.error_code] : [...item.retry_notes] } : item) : ledger.targets; return immutable({ ...clone(ledger), targets, action_attempts: [...ledger.action_attempts, action], submit_action_count: ledger.submit_action_count + (action.action === 'final_submit' ? 1 : 0) }); }
export function recordActionAttempt(ledger, input) { validateLedgerShape(ledger); return appendAction(ledger, normalizeAction(input, ledger.action_attempts.length + 1)); }
export function recordActionBatch(ledger, inputs) { validateLedgerShape(ledger); array(inputs, 'attempts'); if (inputs.length < 2 || inputs.length > 3) fail('attempts', 'batch must contain two or three actions'); if (consumed(ledger)) throw new Phase1StaleReferenceError('observe again after mutation'); const actions = inputs.map((item, index) => normalizeAction(item, ledger.action_attempts.length + index + 1)); const fields = new Set(); actions.forEach((item, index) => { if (item.action !== 'type_text') fail(`attempts[${index}].action`, 'batch accepts type_text only'); if (item.field_id === null || fields.has(item.field_id)) fail(`attempts[${index}].field_id`, 'batch fields must be distinct'); fields.add(item.field_id); bind(ledger, item); }); let next = ledger; for (const item of actions) next = appendAction(next, item, true); return next; }
function normalizeResult(input) { record(input, 'resolution'); exact(input, new Set(['action_id', 'outcome', 'error_code']), 'resolution'); required(input, ['action_id', 'outcome'], 'resolution'); string(input.action_id, 'resolution.action_id', { identifier: true }); string(input.outcome, 'resolution.outcome', { identifier: true }); if (!TERMINAL.has(input.outcome)) fail('resolution.outcome', 'result must be terminal'); const errorCode = input.error_code ?? null; string(errorCode, 'resolution.error_code', { identifier: true, nullable: true }); return { action_id: input.action_id, outcome: input.outcome, error_code: errorCode }; }
export function resolveFinalSubmitAttempt(ledger, input) { validateLedgerShape(ledger); const result = normalizeResult(input); const found = ledger.action_attempts.find((item) => item.action_id === result.action_id); if (!found || found.action !== 'final_submit') fail('resolution.action_id', 'unknown submission', 'UNKNOWN_ACTION'); if (found.outcome !== 'attempted') fail('resolution.action_id', 'submission already resolved', 'ALREADY_RESOLVED'); return immutable({ ...clone(ledger), action_attempts: ledger.action_attempts.map((item) => item.action_id === result.action_id ? { ...item, outcome: result.outcome, error_code: result.error_code } : item) }); }

function canonical(value) { if (value === null || typeof value === 'string' || typeof value === 'boolean') return JSON.stringify(value); if (Array.isArray(value) && value.every((item) => typeof item === 'string')) return JSON.stringify(value); fail('value', 'unsupported private value'); }
export function digestPrivateValue(value) { return createHash('sha256').update(canonical(value), 'utf8').digest('hex'); }
export function digestObservedValue(_target, value) { return digestPrivateValue(value); }

function proofs(input) { if (input == null) return new Map(); record(input, 'retention_proofs'); const result = new Map(); for (const [fieldId, item] of Object.entries(input)) { record(item, `retention_proofs.${fieldId}`); exact(item, PROOF_KEYS, `retention_proofs.${fieldId}`); required(item, ['action_id', 'visually_confirmed'], `retention_proofs.${fieldId}`); string(item.action_id, `retention_proofs.${fieldId}.action_id`, { identifier: true }); boolean(item.visually_confirmed, `retention_proofs.${fieldId}.visually_confirmed`); if (item.file_name !== undefined && item.file_name !== null && (typeof item.file_name !== 'string' || !BASENAME.test(item.file_name))) fail(`retention_proofs.${fieldId}.file_name`, 'invalid basename'); result.set(fieldId, { action_id: item.action_id, visually_confirmed: item.visually_confirmed, file_name: item.file_name ?? null }); } return result; }
function proofAction(ledger, target, proof) { if (!proof?.visually_confirmed) return null; const action = ledger.action_attempts.find((item) => item.action_id === proof.action_id); if (!action || action.outcome !== 'succeeded' || action.stale_target || !TARGET_MUTATIONS.has(action.action) || action.field_id !== target.field_id) return null; return action; }
export function verifyRetention(ledger, observation, supplied = undefined) { validateLedgerShape(ledger); validateObservation(observation); const suppliedProofs = proofs(supplied); const prior = ledger.observation_ids.length > 1 ? ledger.observation_ids.at(-2) : null; if (ledger.latest_observation_id !== observation.observation_id || observation.previous_observation_id !== prior) return immutable({ ledger: clone(ledger), ok: false, retry_required: true, errors: [{ code: 'STALE_OBSERVATION', message: 'retention image is stale' }], retry_notes: ['stale-observation'] }); const current = new Map(observation.targets.map((item) => [item.target_id, item])); const errors = []; const notes = []; const targets = ledger.targets.map((target) => { if (consumed(ledger, observation.observation_id) && ledger.action_attempts.some((item) => item.field_id === target.field_id && item.observation_id === observation.observation_id && !item.stale_target)) { errors.push({ code: 'MUTATION_PENDING', field_id: target.field_id, message: 'pending mutation' }); notes.push(`${target.field_id}:pending-mutation`); return { ...target, retained: false, valid: false }; } if (target.answer_state === 'unresolved' || !target.reachable || !target.present_in_latest_observation) return target; const visual = current.get(target.target_id); if (!visual) { errors.push({ code: 'STALE_TARGET', field_id: target.field_id, message: 'target not current' }); notes.push(`${target.field_id}:stale-target`); return { ...target, retained: false, valid: false }; } const proof = suppliedProofs.get(target.field_id); let retained = false; const issues = []; if (visual.validation.valid !== true) issues.push('validation-error'); if (target.answer_state === 'blank') retained = visual.value_state === target.latest_state.value_state && visual.checked === target.latest_state.checked; else if (target.answer_state === 'answered') { const action = proofAction(ledger, target, proof); if (!proof) issues.push('proof-required'); else if (!action || proof.visually_confirmed !== true) issues.push('invalid-proof'); else if (visual.file?.present && proof.file_name !== null && visual.file.file_name !== proof.file_name) issues.push('invalid-proof'); else retained = true; } if (!retained && issues.length === 0) issues.push('value-not-retained'); for (const issue of issues) { const code = issue === 'validation-error' ? 'INVALID_TARGET' : issue.includes('proof') ? 'INVALID_PROOF' : 'VALUE_NOT_RETAINED'; errors.push({ code, field_id: target.field_id, message: issue }); notes.push(`${target.field_id}:${issue}`); } return { ...target, retained, valid: visual.validation.valid === true && retained, retry_notes: [...target.retry_notes, ...issues.filter((item) => !target.retry_notes.includes(item))] }; }); const next = immutable({ ...clone(ledger), targets }); return immutable({ ledger: next, ok: errors.length === 0, retry_required: errors.length > 0, errors, retry_notes: notes }); }
export function semanticChoiceIsDeliberate(value) { return typeof value === 'string' && CHOICES.has(value); }
export function answerSourceIsAllowed(value) { return typeof value === 'string' && SOURCES.has(value); }
